import {
  Cloud,
  Cpu,
  Database,
  FileJson2,
  Globe2,
  Inbox,
  ListTodo,
  MapPin,
  MonitorCog,
  RadioTower,
  ServerCog,
} from "lucide-react";
import type {
  MonitorEdge,
  MonitorEvent,
  MonitorMetrics,
  MonitorNode,
} from "./types";

export const initialMetrics: MonitorMetrics = {
  workers: 1,
  agentRests: 1,
  probes: 2,
  queued: 3,
  scheduled: 4,
  reports: 24,
};

export const monitorNodes: MonitorNode[] = [
  {
    id: "console",
    title: "M5 Console",
    subtitle: "任务入口",
    category: "CONTROL",
    status: "healthy",
    icon: MonitorCog,
    position: { x: 0, y: 20 },
    metric: "53333",
    metricLabel: "PORT",
    details: [
      { label: "运行模式", value: "Local Console" },
      { label: "监听地址", value: "127.0.0.1:53333", mono: true },
      { label: "最近操作", value: "创建 HTTP 可用性任务" },
      { label: "状态", value: "在线", tone: "healthy" },
    ],
  },
  {
    id: "taskcenter",
    title: "TaskCenter",
    subtitle: "任务定义与持久化",
    category: "SERVICE",
    status: "healthy",
    icon: ListTodo,
    position: { x: 230, y: 20 },
    metric: "4",
    metricLabel: "TASKS",
    details: [
      { label: "监听端口", value: "17005", mono: true },
      { label: "Profile", value: "local", mono: true },
      { label: "任务总数", value: "4" },
      { label: "最近写入", value: "刚刚" },
    ],
  },
  {
    id: "mysql",
    title: "MySQL",
    subtitle: "业务任务与探针库存",
    category: "DATA STORE",
    status: "healthy",
    icon: Database,
    position: { x: 0, y: 250 },
    metric: "7",
    metricLabel: "TABLES",
    details: [
      { label: "数据库", value: "smartalibench", mono: true },
      { label: "监听地址", value: "127.0.0.1:13306", mono: true },
      { label: "探针库存", value: "2 registered" },
      { label: "关键表", value: "sab_task / sab_agent", mono: true },
    ],
  },
  {
    id: "task-redis",
    title: "Redis Task Store",
    subtitle: "任务表与 Worker 心跳",
    category: "DATA STORE",
    status: "healthy",
    icon: Database,
    position: { x: 230, y: 250 },
    metric: "20",
    metricLabel: "BUCKETS",
    details: [
      { label: "监听地址", value: "127.0.0.1:16379", mono: true },
      { label: "Worker 心跳", value: "1 fresh", tone: "healthy" },
      { label: "queueNumber", value: "0-19", mono: true },
      { label: "任务详情", value: "4 cached" },
    ],
  },
  {
    id: "worker",
    title: "Worker",
    subtitle: "扫描、计时与任务分发",
    category: "SCHEDULER",
    status: "healthy",
    icon: Cpu,
    position: { x: 460, y: 20 },
    metric: "1",
    metricLabel: "ONLINE",
    details: [
      { label: "Worker ID", value: "172.17.0.9", mono: true },
      { label: "负责分桶", value: "0-19", mono: true },
      { label: "调度任务", value: "4 scheduled" },
      { label: "心跳", value: "< 60s", tone: "healthy" },
      { label: "本次分发", value: "3 task IDs" },
    ],
  },
  {
    id: "execution-queue",
    title: "Execution Queue",
    subtitle: "待探针消费的 taskId",
    category: "REDIS QUEUE",
    status: "healthy",
    icon: Inbox,
    position: { x: 460, y: 250 },
    metric: "3",
    metricLabel: "QUEUED",
    details: [
      { label: "数据类型", value: "taskId list", mono: true },
      { label: "当前长度", value: "3" },
      { label: "消费方式", value: "RPOP", mono: true },
      { label: "最近写入", value: "worker dispatch" },
    ],
  },
  {
    id: "agent-rest",
    title: "Agent-Rest",
    subtitle: "注册、拉取与报告入口",
    category: "GATEWAY",
    status: "healthy",
    icon: ServerCog,
    position: { x: 690, y: 20 },
    metric: "17008",
    metricLabel: "PORT",
    details: [
      { label: "运行模式", value: "local", mono: true },
      { label: "监听端口", value: "17008", mono: true },
      { label: "已注册探针", value: "2" },
      { label: "最近拉取", value: "2s ago", tone: "healthy" },
      { label: "最近报告", value: "1s ago", tone: "healthy" },
    ],
  },
  {
    id: "probe-idc",
    title: "GoProbe IDC",
    subtitle: "测试市 · IDC",
    category: "PROBE",
    status: "healthy",
    icon: MapPin,
    position: { x: 920, y: -30 },
    metric: "5s",
    metricLabel: "PULL",
    details: [
      {
        label: "Client ID",
        value: "6822ebe9-47c8-47da-b361-81c62605839e",
        mono: true,
      },
      { label: "版本", value: "v2.7.35", mono: true },
      { label: "类型", value: "IDC" },
      { label: "拉取周期", value: "5s" },
      { label: "CPU", value: "0.1%" },
      { label: "内存", value: "0.6%" },
      { label: "最近上报", value: "刚刚", tone: "healthy" },
    ],
  },
  {
    id: "probe-pc",
    title: "GoProbe PC",
    subtitle: "北京市 · PC",
    category: "PROBE",
    status: "healthy",
    icon: RadioTower,
    position: { x: 920, y: 70 },
    metric: "10s",
    metricLabel: "PULL",
    details: [
      {
        label: "Client ID",
        value: "a6c812b1-1952-485b-9bf3-2d1c26ac6e4b",
        mono: true,
      },
      { label: "版本", value: "v2.7.35", mono: true },
      { label: "类型", value: "PC / Lastmile" },
      { label: "拉取周期", value: "10s ± 3s" },
      { label: "任务数量", value: "3" },
      { label: "最近上报", value: "刚刚", tone: "healthy" },
    ],
  },
  {
    id: "target",
    title: "www.aliyun.com",
    subtitle: "HTTP 可用性目标",
    category: "TARGET",
    status: "healthy",
    icon: Globe2,
    position: { x: 1150, y: 20 },
    metric: "200",
    metricLabel: "HTTP",
    details: [
      { label: "协议", value: "HTTPS" },
      { label: "状态码", value: "200", tone: "healthy" },
      { label: "总耗时", value: "138 ms" },
      { label: "远端地址", value: "1.71.67.25", mono: true },
      { label: "断言", value: "通过", tone: "healthy" },
    ],
  },
  {
    id: "ndjson",
    title: "reports.ndjson",
    subtitle: "本地报告副本",
    category: "LOCAL SINK",
    status: "healthy",
    icon: FileJson2,
    position: { x: 460, y: 470 },
    metric: "24",
    metricLabel: "REPORTS",
    details: [
      { label: "写入模式", value: "append only" },
      {
        label: "路径",
        value: "/var/lib/m2/agent-rest/reports.ndjson",
        mono: true,
      },
      { label: "最近写入", value: "1s ago", tone: "healthy" },
      { label: "Topic", value: "http", mono: true },
    ],
  },
  {
    id: "agent-cache",
    title: "Agent Cache",
    subtitle: "探针路由与队列定位",
    category: "REDIS CACHE",
    status: "healthy",
    icon: Database,
    position: { x: 900, y: 250 },
    metric: "2",
    metricLabel: "CLIENTS",
    details: [
      { label: "数据类型", value: "AgentCache", mono: true },
      { label: "已注册探针", value: "2" },
      { label: "用途", value: "生成 execution queue key" },
      { label: "TTL", value: "keepalive refreshed", tone: "healthy" },
    ],
  },
  {
    id: "sls",
    title: "SLS Logstore",
    subtitle: "测试环境持久化",
    category: "REMOTE SINK",
    status: "healthy",
    icon: Cloud,
    position: { x: 900, y: 470 },
    metric: "OK",
    metricLabel: "DELIVERY",
    details: [
      {
        label: "Project",
        value: "syn-synthetic-monitoring-system-test",
        mono: true,
      },
      { label: "Logstore", value: "sitemonitor_log", mono: true },
      { label: "地域", value: "cn-shanghai", mono: true },
      { label: "最近投递", value: "success", tone: "healthy" },
    ],
  },
];

export const monitorEdges: MonitorEdge[] = [
  {
    id: "console-taskcenter",
    source: "console",
    target: "taskcenter",
    label: "创建 / 修改任务",
    flow: "task",
    sourceHandle: "right-out",
    targetHandle: "left-in",
    routePoints: [{ x: 209, y: 59 }],
    labelPosition: { x: 209, y: 4 },
  },
  {
    id: "taskcenter-mysql",
    source: "taskcenter",
    target: "mysql",
    label: "业务记录",
    flow: "control",
    sourceHandle: "left-out",
    targetHandle: "right-in",
    routePoints: [
      { x: 209, y: 59 },
      { x: 209, y: 289 },
    ],
    labelPosition: { x: 209, y: 174 },
  },
  {
    id: "taskcenter-redis",
    source: "taskcenter",
    target: "task-redis",
    label: "写入 Task Detail",
    flow: "task",
    sourceHandle: "bottom-out",
    targetHandle: "top-in",
    routePoints: [{ x: 324, y: 174 }],
    labelPosition: { x: 324, y: 174 },
  },
  {
    id: "redis-worker",
    source: "task-redis",
    target: "worker",
    label: "读取到期任务",
    flow: "task",
    sourceHandle: "right-out",
    targetHandle: "left-in",
    routePoints: [
      { x: 445, y: 289 },
      { x: 445, y: 59 },
    ],
    labelPosition: { x: 445, y: 174 },
  },
  {
    id: "worker-execution",
    source: "worker",
    target: "execution-queue",
    label: "LPUSH taskId",
    flow: "task",
    sourceHandle: "bottom-out",
    targetHandle: "top-in",
    routePoints: [{ x: 554, y: 174 }],
    labelPosition: { x: 554, y: 174 },
  },
  {
    id: "execution-agentrest",
    source: "execution-queue",
    target: "agent-rest",
    label: "RPOP + loadDetail",
    flow: "task",
    sourceHandle: "right-out",
    targetHandle: "left-in",
    routePoints: [
      { x: 675, y: 289 },
      { x: 675, y: 59 },
    ],
    labelPosition: { x: 675, y: 174 },
  },
  {
    id: "agentrest-idc",
    source: "agent-rest",
    target: "probe-idc",
    label: "拉取 / 返回 / 上报",
    flow: "control",
    sourceHandle: "right-out",
    targetHandle: "left-in",
    routePoints: [
      { x: 894, y: 59 },
      { x: 894, y: 9 },
    ],
    labelPosition: { x: 894, y: -8 },
  },
  {
    id: "agentrest-pc",
    source: "agent-rest",
    target: "probe-pc",
    label: "拉取 / 返回 / 上报",
    flow: "control",
    sourceHandle: "right-out",
    targetHandle: "left-in",
    routePoints: [
      { x: 894, y: 59 },
      { x: 894, y: 109 },
    ],
    labelPosition: { x: 894, y: 126 },
  },
  {
    id: "idc-target",
    source: "probe-idc",
    target: "target",
    label: "探测请求 / 响应",
    flow: "task",
    sourceHandle: "right-out",
    targetHandle: "left-in",
    routePoints: [
      { x: 1129, y: 9 },
      { x: 1129, y: 59 },
    ],
    labelPosition: { x: 1129, y: -8 },
  },
  {
    id: "pc-target",
    source: "probe-pc",
    target: "target",
    label: "探测请求 / 响应",
    flow: "task",
    sourceHandle: "right-out",
    targetHandle: "left-in",
    routePoints: [
      { x: 1129, y: 109 },
      { x: 1129, y: 59 },
    ],
    labelPosition: { x: 1129, y: 126 },
  },
  {
    id: "agentrest-ndjson",
    source: "agent-rest",
    target: "ndjson",
    label: "本地落盘",
    flow: "report",
    sourceHandle: "bottom-out",
    targetHandle: "top-in",
    routePoints: [
      { x: 784, y: 155 },
      { x: 1118, y: 155 },
      { x: 1118, y: 420 },
      { x: 554, y: 420 },
    ],
    labelPosition: { x: 834, y: 420 },
  },
  {
    id: "agentrest-agentcache",
    source: "agent-rest",
    target: "agent-cache",
    label: "注册 / keepalive",
    flow: "control",
    sourceHandle: "bottom-out",
    targetHandle: "top-in",
    routePoints: [
      { x: 784, y: 175 },
      { x: 994, y: 175 },
    ],
    labelPosition: { x: 889, y: 175 },
  },
  {
    id: "agentrest-sls",
    source: "agent-rest",
    target: "sls",
    label: "异步投递",
    flow: "report",
    sourceHandle: "bottom-out",
    targetHandle: "top-in",
    routePoints: [
      { x: 784, y: 165 },
      { x: 1130, y: 165 },
      { x: 1130, y: 430 },
      { x: 994, y: 430 },
    ],
    labelPosition: { x: 1062, y: 430 },
  },
];

type EventTemplate = Omit<MonitorEvent, "id" | "timestamp" | "step">;

export const eventTemplates: EventTemplate[] = [
  {
    kind: "probe-register",
    title: "GoProbe 注册并获取 Client ID",
    detail: "register 请求由 AgentController 接收",
    edgeId: "agentrest-pc",
    direction: "reverse",
    sourceId: "probe-pc",
    targetId: "agent-rest",
    severity: "info",
    taskId: "bootstrap",
    clientId: "a6c812b1-1952-485b-9bf3-2d1c26ac6e4b",
  },
  {
    kind: "agent-cached",
    title: "Agent-Rest 刷新探针缓存",
    detail: "AgentCache 已写入 Redis，本地闭环可据此定位队列",
    edgeId: "agentrest-agentcache",
    direction: "forward",
    sourceId: "agent-rest",
    targetId: "agent-cache",
    severity: "info",
    taskId: "bootstrap",
    clientId: "a6c812b1-1952-485b-9bf3-2d1c26ac6e4b",
  },
  {
    kind: "task-created",
    title: "控制台提交拨测任务",
    detail: "HTTP 可用性任务进入 TaskCenter",
    edgeId: "console-taskcenter",
    direction: "forward",
    sourceId: "console",
    targetId: "taskcenter",
    severity: "info",
    taskId: "330b473e-f30c-488a-bf7b-c0a834321d13",
  },
  {
    kind: "task-saved",
    title: "TaskCenter 保存业务记录",
    detail: "sab_task 已更新",
    edgeId: "taskcenter-mysql",
    direction: "forward",
    sourceId: "taskcenter",
    targetId: "mysql",
    severity: "info",
    taskId: "330b473e-f30c-488a-bf7b-c0a834321d13",
  },
  {
    kind: "task-published",
    title: "任务进入 Redis 任务表",
    detail: "queueNumber=12，等待 Worker 扫描",
    edgeId: "taskcenter-redis",
    direction: "forward",
    sourceId: "taskcenter",
    targetId: "task-redis",
    severity: "info",
    taskId: "330b473e-f30c-488a-bf7b-c0a834321d13",
  },
  {
    kind: "worker-scan",
    title: "Worker 扫描到任务",
    detail: "Worker 172.17.0.9 管理 queueNumber 0-19",
    edgeId: "redis-worker",
    direction: "forward",
    sourceId: "task-redis",
    targetId: "worker",
    severity: "info",
    taskId: "330b473e-f30c-488a-bf7b-c0a834321d13",
  },
  {
    kind: "worker-dispatch",
    title: "任务到期并完成投放",
    detail: "taskId 已写入 execution queue",
    edgeId: "worker-execution",
    direction: "forward",
    sourceId: "worker",
    targetId: "execution-queue",
    severity: "info",
    taskId: "330b473e-f30c-488a-bf7b-c0a834321d13",
  },
  {
    kind: "probe-fetch",
    title: "PC 探针发起拉取",
    detail: "get_tasks count=600",
    edgeId: "agentrest-pc",
    direction: "reverse",
    sourceId: "probe-pc",
    targetId: "agent-rest",
    severity: "info",
    taskId: "330b473e-f30c-488a-bf7b-c0a834321d13",
    clientId: "a6c812b1-1952-485b-9bf3-2d1c26ac6e4b",
  },
  {
    kind: "queue-pop",
    title: "Agent-Rest 消费执行队列",
    detail: "RPOP taskId 后加载最新 TaskDetail",
    edgeId: "execution-agentrest",
    direction: "forward",
    sourceId: "execution-queue",
    targetId: "agent-rest",
    severity: "info",
    taskId: "330b473e-f30c-488a-bf7b-c0a834321d13",
    clientId: "a6c812b1-1952-485b-9bf3-2d1c26ac6e4b",
  },
  {
    kind: "task-delivered",
    title: "完整任务 JSON 返回探针",
    detail: "PC 探针接收并装载任务",
    edgeId: "agentrest-pc",
    direction: "forward",
    sourceId: "agent-rest",
    targetId: "probe-pc",
    severity: "info",
    taskId: "330b473e-f30c-488a-bf7b-c0a834321d13",
    clientId: "a6c812b1-1952-485b-9bf3-2d1c26ac6e4b",
  },
  {
    kind: "probe-request",
    title: "GoProbe 执行 HTTP 探测",
    detail: "GET https://www.aliyun.com",
    edgeId: "pc-target",
    direction: "forward",
    sourceId: "probe-pc",
    targetId: "target",
    severity: "info",
    taskId: "330b473e-f30c-488a-bf7b-c0a834321d13",
    clientId: "a6c812b1-1952-485b-9bf3-2d1c26ac6e4b",
  },
  {
    kind: "probe-response",
    title: "目标返回 HTTP 200",
    detail: "总耗时 138 ms，断言通过",
    edgeId: "pc-target",
    direction: "reverse",
    sourceId: "target",
    targetId: "probe-pc",
    severity: "info",
    taskId: "330b473e-f30c-488a-bf7b-c0a834321d13",
    clientId: "a6c812b1-1952-485b-9bf3-2d1c26ac6e4b",
  },
  {
    kind: "report-upload",
    title: "GoProbe 上报探测结果",
    detail: "function=report，raw_exception={}",
    edgeId: "agentrest-pc",
    direction: "reverse",
    sourceId: "probe-pc",
    targetId: "agent-rest",
    severity: "info",
    taskId: "330b473e-f30c-488a-bf7b-c0a834321d13",
    clientId: "a6c812b1-1952-485b-9bf3-2d1c26ac6e4b",
  },
  {
    kind: "report-local",
    title: "报告写入本地 NDJSON",
    detail: "reports.ndjson 追加成功",
    edgeId: "agentrest-ndjson",
    direction: "forward",
    sourceId: "agent-rest",
    targetId: "ndjson",
    severity: "info",
    taskId: "330b473e-f30c-488a-bf7b-c0a834321d13",
    clientId: "a6c812b1-1952-485b-9bf3-2d1c26ac6e4b",
  },
  {
    kind: "report-sls",
    title: "SLS 异步投递成功",
    detail: "sitemonitor_log 已确认接收",
    edgeId: "agentrest-sls",
    direction: "forward",
    sourceId: "agent-rest",
    targetId: "sls",
    severity: "info",
    taskId: "330b473e-f30c-488a-bf7b-c0a834321d13",
    clientId: "a6c812b1-1952-485b-9bf3-2d1c26ac6e4b",
  },
];
