"use strict";

const probeHealthSnapshot = {
  schema_version: "1.0",
  window: {
    start: "2026-07-27T10:20:00+08:00",
    end: "2026-07-27T10:30:00+08:00",
  },
  thresholds: {
    offline_seconds: 180,
    minimum_peer_count: 3,
  },
  input: {
    source: "mock-sls",
    workspace: "synthetic-monitoring-system-test",
  },
  summary: {
    healthy: 3272,
    suspected: 7,
    abnormal: 1,
    insufficient_evidence: 0,
  },
  nodes: [
    {
      client_id: "probe-cn-shanghai-07",
      status: "abnormal",
      status_label: "故障",
      boundary: "探针节点异常",
      confidence: "high",
      window: {
        start: "2026-07-27T10:20:00+08:00",
        end: "2026-07-27T10:30:00+08:00",
      },
      identity: {
        region: "华南",
        city: "上海市",
        isp: "阿里云",
        probe_type: "IDC",
        version: "v2.7.35",
      },
      metrics: {
        report_count: 186,
        failed_report_count: 181,
        affected_task_count: 26,
        affected_target_count: 14,
        peer_healthy_count: 32,
      },
      evidence_planes: {
        online: {
          observed: true,
          latest_agent_state: 2,
          latest_observed_at: "2026-07-27T10:29:42+08:00",
        },
        report: {
          observed: true,
          failure_ratio: 0.973,
          last_success_at: "2026-07-27T10:20:31+08:00",
        },
        peer: {
          observed: true,
          healthy_peer_count: 32,
          peer_failure_ratio: 0.018,
        },
      },
      reasons: [
        "同一探针在多个任务、多个目标上持续出现宽泛失败。",
        "同地域同运营商的 32 个对照探针保持健康。",
        "online 记录显示 agent_state=2，探针自检状态异常。",
      ],
      data_gaps: [
        "当前没有主机进程日志，无法继续定位到进程、网络栈或宿主机层。",
      ],
      observed_agent_states: [1, 2],
    },
  ],
};

const onlineNodes = [
  {
    id: "worker-east",
    title: "华东 Worker",
    subtitle: "任务扫描与区域调度",
    category: "WORKER GROUP",
    entityType: "synthetics.worker.group",
    region: "cn-east",
    status: "healthy",
    position: { x: 30, y: 20 },
    metric: "9",
    metricLabel: "WORKERS",
    memberCount: 9,
    statusCounts: { healthy: 9, suspected: 0, abnormal: 0, insufficient_evidence: 0 },
    details: [
      { label: "实体来源", value: "UModel worker group" },
      { label: "地域", value: "华东" },
      { label: "在线实例", value: "9 / 9" },
      { label: "状态依据", value: "heartbeat + dispatch" },
    ],
  },
  {
    id: "agent-east",
    title: "华东 Agent-Rest",
    subtitle: "探针接入与任务分发",
    category: "AGENT-REST GROUP",
    entityType: "synthetics.agent_rest.group",
    region: "cn-east",
    status: "healthy",
    position: { x: 340, y: 20 },
    metric: "18",
    metricLabel: "INSTANCES",
    memberCount: 18,
    statusCounts: { healthy: 18, suspected: 0, abnormal: 0, insufficient_evidence: 0 },
    details: [
      { label: "实体来源", value: "UModel agent-rest group" },
      { label: "地域", value: "华东" },
      { label: "在线实例", value: "18 / 18" },
      { label: "近一分钟交互", value: "6,420" },
    ],
  },
  {
    id: "probe-east",
    title: "华东 GoProbe",
    subtitle: "区域探针聚合",
    category: "GOPROBE GROUP",
    entityType: "synthetics.probe.group",
    region: "cn-east",
    status: "healthy",
    position: { x: 650, y: 20 },
    metric: "1,240",
    metricLabel: "PROBES",
    memberCount: 1240,
    statusCounts: { healthy: 1240, suspected: 0, abnormal: 0, insufficient_evidence: 0 },
    ordinaryProbeStatus: "healthy",
    idcProbes: [
      {
        id: "probe-east-idc-01",
        title: "上海 IDC-01",
        subtitle: "机房探针",
        status: "healthy",
        details: [
          { label: "探针类型", value: "IDC" },
          { label: "地域", value: "华东 / 上海" },
          { label: "运行状态", value: "正常" },
        ],
      },
      {
        id: "probe-east-idc-02",
        title: "杭州 IDC-02",
        subtitle: "机房探针",
        status: "healthy",
        details: [
          { label: "探针类型", value: "IDC" },
          { label: "地域", value: "华东 / 杭州" },
          { label: "运行状态", value: "正常" },
        ],
      },
      {
        id: "probe-east-idc-03",
        title: "南京 IDC-03",
        subtitle: "机房探针",
        status: "healthy",
        details: [
          { label: "探针类型", value: "IDC" },
          { label: "地域", value: "华东 / 南京" },
          { label: "运行状态", value: "正常" },
        ],
      },
    ],
    diagnosis: {
      status: "healthy",
      statusLabel: "正常",
      confidence: "high",
      boundary: "区域探针整体健康",
    },
    details: [
      { label: "判定来源", value: "probe-health-analysis" },
      { label: "正常", value: "1,240" },
      { label: "疑似", value: "0" },
      { label: "故障", value: "0" },
      { label: "运行数据", value: "拨测报告 + online 心跳" },
    ],
  },
  {
    id: "worker-north",
    title: "华北 Worker",
    subtitle: "任务扫描与区域调度",
    category: "WORKER GROUP",
    entityType: "synthetics.worker.group",
    region: "cn-north",
    status: "healthy",
    position: { x: 30, y: 190 },
    metric: "8",
    metricLabel: "WORKERS",
    memberCount: 8,
    statusCounts: { healthy: 8, suspected: 0, abnormal: 0, insufficient_evidence: 0 },
    details: [
      { label: "实体来源", value: "UModel worker group" },
      { label: "地域", value: "华北" },
      { label: "在线实例", value: "8 / 8" },
      { label: "状态依据", value: "heartbeat + dispatch" },
    ],
  },
  {
    id: "agent-north",
    title: "华北 Agent-Rest",
    subtitle: "探针接入与任务分发",
    category: "AGENT-REST GROUP",
    entityType: "synthetics.agent_rest.group",
    region: "cn-north",
    status: "healthy",
    position: { x: 340, y: 190 },
    metric: "15",
    metricLabel: "INSTANCES",
    memberCount: 15,
    statusCounts: { healthy: 15, suspected: 0, abnormal: 0, insufficient_evidence: 0 },
    details: [
      { label: "实体来源", value: "UModel agent-rest group" },
      { label: "地域", value: "华北" },
      { label: "在线实例", value: "15 / 15" },
      { label: "近一分钟交互", value: "5,980" },
    ],
  },
  {
    id: "probe-north",
    title: "华北 GoProbe",
    subtitle: "7 个探针进入疑似状态",
    category: "GOPROBE GROUP",
    entityType: "synthetics.probe.group",
    region: "cn-north",
    status: "warning",
    position: { x: 650, y: 190 },
    metric: "1,011",
    metricLabel: "PROBES",
    memberCount: 1011,
    statusCounts: { healthy: 1004, suspected: 7, abnormal: 0, insufficient_evidence: 0 },
    ordinaryProbeStatus: "warning",
    idcProbes: [
      {
        id: "probe-north-idc-01",
        title: "北京 IDC-01",
        subtitle: "机房探针",
        status: "healthy",
        details: [
          { label: "探针类型", value: "IDC" },
          { label: "地域", value: "华北 / 北京" },
          { label: "运行状态", value: "正常" },
        ],
      },
      {
        id: "probe-north-idc-02",
        title: "天津 IDC-02",
        subtitle: "机房探针",
        status: "healthy",
        details: [
          { label: "探针类型", value: "IDC" },
          { label: "地域", value: "华北 / 天津" },
          { label: "运行状态", value: "正常" },
        ],
      },
      {
        id: "probe-north-idc-03",
        title: "青岛 IDC-03",
        subtitle: "机房探针",
        status: "healthy",
        details: [
          { label: "探针类型", value: "IDC" },
          { label: "地域", value: "华北 / 青岛" },
          { label: "运行状态", value: "正常" },
        ],
      },
    ],
    diagnosis: {
      status: "suspected",
      statusLabel: "疑似异常",
      confidence: "medium",
      boundary: "证据尚未满足故障硬门禁",
    },
    details: [
      { label: "判定来源", value: "probe-health-analysis" },
      { label: "正常", value: "1,004" },
      { label: "疑似", value: "7", tone: "warning" },
      { label: "故障", value: "0" },
      { label: "运行数据", value: "拨测报告 + online 心跳" },
    ],
  },
  {
    id: "worker-south",
    title: "华南 Worker",
    subtitle: "任务扫描与区域调度",
    category: "WORKER GROUP",
    entityType: "synthetics.worker.group",
    region: "cn-south",
    status: "healthy",
    position: { x: 30, y: 360 },
    metric: "7",
    metricLabel: "WORKERS",
    memberCount: 7,
    statusCounts: { healthy: 7, suspected: 0, abnormal: 0, insufficient_evidence: 0 },
    details: [
      { label: "实体来源", value: "UModel worker group" },
      { label: "地域", value: "华南" },
      { label: "在线实例", value: "7 / 7" },
      { label: "状态依据", value: "heartbeat + dispatch" },
    ],
  },
  {
    id: "agent-south",
    title: "华南 Agent-Rest",
    subtitle: "探针接入与任务分发",
    category: "AGENT-REST GROUP",
    entityType: "synthetics.agent_rest.group",
    region: "cn-south",
    status: "healthy",
    position: { x: 340, y: 360 },
    metric: "15",
    metricLabel: "INSTANCES",
    memberCount: 15,
    statusCounts: { healthy: 15, suspected: 0, abnormal: 0, insufficient_evidence: 0 },
    details: [
      { label: "实体来源", value: "UModel agent-rest group" },
      { label: "地域", value: "华南" },
      { label: "在线实例", value: "15 / 15" },
      { label: "近一分钟交互", value: "6,020" },
    ],
  },
  {
    id: "probe-south",
    title: "华南 GoProbe",
    subtitle: "1 个故障探针，区域整体受影响",
    category: "GOPROBE GROUP",
    entityType: "synthetics.probe.group",
    region: "cn-south",
    status: "warning",
    position: { x: 650, y: 360 },
    metric: "1,029",
    metricLabel: "PROBES",
    memberCount: 1029,
    incidentId: "INC-1042",
    statusCounts: { healthy: 1028, suspected: 0, abnormal: 1, insufficient_evidence: 0 },
    ordinaryProbeStatus: "healthy",
    idcProbes: [
      {
        id: "probe-south-idc-01",
        title: "广州 IDC-01",
        subtitle: "机房探针",
        status: "healthy",
        details: [
          { label: "探针类型", value: "IDC" },
          { label: "地域", value: "华南 / 广州" },
          { label: "运行状态", value: "正常" },
        ],
      },
      {
        id: "probe-south-idc-02",
        title: "深圳 IDC-02",
        subtitle: "机房探针",
        status: "healthy",
        details: [
          { label: "探针类型", value: "IDC" },
          { label: "地域", value: "华南 / 深圳" },
          { label: "运行状态", value: "正常" },
        ],
      },
      {
        id: "probe-cn-shanghai-07",
        title: "IDC 机房-07",
        subtitle: "已确认探针故障",
        status: "error",
        incidentId: "INC-1042",
        details: [
          { label: "探针类型", value: "IDC" },
          { label: "Client ID", value: "probe-cn-shanghai-07", mono: true },
          { label: "失败报告", value: "181 / 186", tone: "error" },
        ],
      },
      {
        id: "probe-south-idc-03",
        title: "厦门 IDC-03",
        subtitle: "机房探针",
        status: "healthy",
        details: [
          { label: "探针类型", value: "IDC" },
          { label: "地域", value: "华南 / 厦门" },
          { label: "运行状态", value: "正常" },
        ],
      },
    ],
    diagnosis: {
      status: "abnormal",
      statusLabel: "含故障节点",
      confidence: "high",
      boundary: "区域内存在已确认探针节点异常",
    },
    details: [
      { label: "判定来源", value: "probe-health-analysis" },
      { label: "正常", value: "1,028" },
      { label: "疑似", value: "0" },
      { label: "故障", value: "1", tone: "error" },
      { label: "运行数据", value: "拨测报告 + online 心跳" },
    ],
  },
];

const laneEdges = [
  ["east-worker-agent", "worker-east", "agent-east", "任务调度", "task", "info"],
  ["east-agent-probe", "agent-east", "probe-east", "拉取 / 上报", "control", "info"],
  ["north-worker-agent", "worker-north", "agent-north", "任务调度", "task", "info"],
  ["north-agent-probe", "agent-north", "probe-north", "拉取 / 上报", "control", "warning"],
  ["south-worker-agent", "worker-south", "agent-south", "任务调度", "task", "info"],
  ["south-agent-probe", "agent-south", "probe-south", "拉取 / 上报", "control", "warning"],
].map(([id, source, target, label, flow, severity]) => ({
  id,
  source,
  target,
  label,
  flow,
  severity,
}));

const incident = {
  id: "INC-1042",
  title: "华南单探针故障",
  status: "abnormal",
  statusLabel: "故障",
  confidence: "high",
  boundary: "探针节点异常",
  affectedGroupId: "probe-south",
  rootEntityId: "probe-cn-shanghai-07",
  startedAt: "2026-07-27T10:21:06+08:00",
  updatedAt: "2026-07-27T10:29:42+08:00",
  summary:
    "probe-cn-shanghai-07 在多任务、多目标上持续宽泛失败，同地域对照探针健康，且自检状态异常；证据支持将问题定界到该探针节点。",
  skill: {
    id: "skill.cms2.synthetics.probe-health-analysis",
    version: "v1.0.0",
    source: "mock-sls",
  },
  affected: {
    tasks: 26,
    targets: 14,
    probes: 1,
  },
  reasons: probeHealthSnapshot.nodes[0].reasons,
  dataGaps: probeHealthSnapshot.nodes[0].data_gaps,
  evidencePlanes: probeHealthSnapshot.nodes[0].evidence_planes,
  timeline: [
    {
      at: "10:21:06",
      title: "宽泛失败开始",
      detail: "多个任务和目标同时出现失败。",
      severity: "warning",
    },
    {
      at: "10:23:18",
      title: "对照探针保持健康",
      detail: "同地域同运营商的 32 个探针未出现同类异常。",
      severity: "info",
    },
    {
      at: "10:29:42",
      title: "满足故障硬门禁",
      detail: "报告面、在线面与同群对照证据共同指向探针节点。",
      severity: "error",
    },
  ],
  graph: {
    nodes: [
      {
        id: "incident-worker",
        title: "华南 Worker",
        subtitle: "调度正常",
        category: "WORKER",
        entityType: "synthetics.worker",
        status: "healthy",
        position: { x: 20, y: 115 },
        metric: "OK",
        metricLabel: "DISPATCH",
        details: [{ label: "结论", value: "任务调度正常" }],
      },
      {
        id: "incident-queue",
        title: "Execution Queue",
        subtitle: "出入队正常",
        category: "REDIS QUEUE",
        entityType: "synthetics.execution_queue",
        status: "healthy",
        position: { x: 250, y: 115 },
        metric: "OK",
        metricLabel: "QUEUE",
        details: [{ label: "结论", value: "未发现任务积压" }],
      },
      {
        id: "incident-agent",
        title: "Agent-Rest",
        subtitle: "拉取与上报通道正常",
        category: "AGENT-REST",
        entityType: "synthetics.agent_rest",
        status: "healthy",
        position: { x: 480, y: 115 },
        metric: "OK",
        metricLabel: "CHANNEL",
        details: [{ label: "结论", value: "同组其他探针交互正常" }],
      },
      {
        id: "incident-probe",
        title: "probe-cn-shanghai-07",
        subtitle: "已确认探针节点异常",
        category: "GOPROBE",
        entityType: "synthetics.probe",
        status: "error",
        position: { x: 710, y: 115 },
        metric: "181",
        metricLabel: "FAILURES",
        incidentId: "INC-1042",
        diagnosis: {
          status: "abnormal",
          statusLabel: "故障",
          confidence: "high",
          boundary: "探针节点异常",
        },
        details: [
          { label: "Client ID", value: "probe-cn-shanghai-07", mono: true },
          { label: "失败报告", value: "181 / 186", tone: "error" },
          { label: "影响任务", value: "26" },
          { label: "影响目标", value: "14" },
        ],
      },
      {
        id: "incident-affected",
        title: "受影响拨测任务",
        subtitle: "26 个任务 / 14 个目标",
        category: "IMPACT",
        entityType: "synthetics.task.group",
        status: "warning",
        position: { x: 940, y: 35 },
        metric: "26",
        metricLabel: "TASKS",
        details: [
          { label: "任务数", value: "26" },
          { label: "目标数", value: "14" },
        ],
      },
      {
        id: "incident-peer",
        title: "同群对照探针",
        subtitle: "32 个对照节点保持健康",
        category: "PEER CONTROL",
        entityType: "synthetics.probe.peer_group",
        status: "healthy",
        position: { x: 940, y: 210 },
        metric: "32",
        metricLabel: "HEALTHY",
        details: [{ label: "用途", value: "排除区域性网络或目标故障" }],
      },
    ],
    edges: [
      {
        id: "incident-worker-queue",
        source: "incident-worker",
        target: "incident-queue",
        label: "投放正常",
        flow: "task",
        severity: "info",
      },
      {
        id: "incident-queue-agent",
        source: "incident-queue",
        target: "incident-agent",
        label: "消费正常",
        flow: "task",
        severity: "info",
      },
      {
        id: "incident-agent-probe",
        source: "incident-agent",
        target: "incident-probe",
        label: "通道正常",
        flow: "control",
        severity: "info",
      },
      {
        id: "incident-probe-affected",
        source: "incident-probe",
        target: "incident-affected",
        label: "宽泛失败",
        flow: "report",
        severity: "error",
      },
      {
        id: "incident-agent-peer",
        source: "incident-agent",
        target: "incident-peer",
        label: "同群对照",
        flow: "control",
        severity: "info",
      },
    ],
  },
};

const eventTemplates = [
  {
    kind: "worker-dispatch",
    title: "华东 Worker 完成区域调度",
    detail: "任务已按区域路由到 Agent-Rest 集群。",
    edgeId: "east-worker-agent",
    sourceId: "worker-east",
    targetId: "agent-east",
    severity: "info",
  },
  {
    kind: "probe-fetch",
    title: "华北探针批次拉取任务",
    detail: "Agent-Rest 与 GoProbe 交互成功；7 个节点仍处于疑似状态。",
    edgeId: "north-agent-probe",
    sourceId: "agent-north",
    targetId: "probe-north",
    severity: "warning",
  },
  {
    kind: "report-upload",
    title: "华东 GoProbe 持续上报",
    detail: "GoProbe 的拨测报告与 online 心跳已回传 Agent-Rest。",
    edgeId: "east-agent-probe",
    sourceId: "probe-east",
    targetId: "agent-east",
    direction: "reverse",
    severity: "info",
  },
  {
    kind: "diagnosis-updated",
    title: "探针健康 Skill 更新故障结论",
    detail: "probe-cn-shanghai-07 满足故障硬门禁，置信度高。",
    edgeId: "south-agent-probe",
    sourceId: "probe-south",
    targetId: "agent-south",
    direction: "reverse",
    severity: "error",
    incidentId: "INC-1042",
  },
  {
    kind: "report-upload",
    title: "华南报告链路仍在工作",
    detail: "故障探针仍有报告，不能把故障误判为上报链路中断。",
    edgeId: "south-agent-probe",
    sourceId: "probe-south",
    targetId: "agent-south",
    direction: "reverse",
    severity: "warning",
    incidentId: "INC-1042",
  },
];

module.exports = {
  incident,
  laneEdges,
  onlineNodes,
  probeHealthSnapshot,
  eventTemplates,
};
